require("dotenv").config();
const express = require("express");
const cors = require("cors");
const nodemailer = require('nodemailer');
const htmlToText = require('html-to-text');


// config >  nodemailer
const transporter = nodemailer.createTransport({
  service: 'Gmail',
  auth: {
    user: process.env.user,
    pass: process.env.mailerhamza
  }
});

const server = express();
server.use(express.json());
server.use(
  cors({
    origin: "http://localhost:3000",
  })
);


// rabbitmq
const amqp = require("amqplib");
let connection, tunnel;
const queue_logs = 'service_email_hamza';

async function connecttorabbit() {
  const server = "amqp://guest:guest@localhost:5672";
  connection = await amqp.connect(server);
  tunnel = await connection.createChannel();

}
 var dataa;
connecttorabbit().then(()=>{
  tunnel.consume(queue_logs,(data)=>{
    console.log("logs =>  " +  data.content.toString());
    dataa=JSON.parse(data.content.toString())
    tunnel.ack(data);
  })
})

server.get('/send-logs-by-email-to-admin', (req, res) => {
 
  // configuration
  const mailOptions = {
    from: {
      name: 'M A S T E R',
      address: 'MASTER@hotmail.com',
    },
    to: process.env.user,
    subject: 'M A S T E R',
    html: '<p style="color:red;font-weight:bold;text-align:center">Generated By Hamza</p><br>' +
      '<p style="color:blue;font-weight:bold;">Username : ' + dataa.fullname + '</p><br>' +
      '<p style="color:blue;font-weight:bold;">Nubmber of created postit: ' + dataa.nbPostit + '</p><br>' +
      '<p style="color:blue;font-weight:bold;">Login_at : ' + dataa.loginAt + '</p><br>'
  }
  // Send Logs operations
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log('Error occurred while sending email:', error.message);
      res.status(500).send('Error occurred while sending email');
    } else {
      console.log('Email sent successfully!', info.response);
      res.send('Email sent successfully!');
    }
  });
}
)



// server listen
server.listen(process.env.port, () => {
  console.log("server running with success...");
})
