version: '3'
services:
  app:
    image: ./app/
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build: ./server/
    ports:
      - 1337:1337
    depends_on:
      - database
      - rabbit
    restart: always
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: always
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped 
  emails:
      build: ./emails/
      ports:
        - 1338:1338
      depends_on:
        - database
        - rabbit
      restart: unless-stopped
  router:
    image: nginx:latest
    ports:
      - 80:80
    volumes: 
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"

volumes:
  mongodb: